### ISSUE TITLE
python-3.10.x - AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by martin-a-brown** [tLDP/python-tldp#9]
It looks like a newer python version, 3.10.x (or somewhere in-between the earlier versions) has at least one breaking change for the `ldptool` dependencies.

The Ubuntu 18.04 system is no longer supported.  When trying to run the `ldptool` under Ubuntu 22.04 (Jammy Jellyfish), the Python version is 3.10.4.

The symptom is the MutableMapping, however, the general class of problem should be addressed.  The `python-tldp` package should be updated to support newer Python and any other necessary libraries.

-Martin

**Comment by pbiering** [comment]
Is there no "legacy" older version of Python available for Ubuntu 22.04 LTS?

on AlmaLinux (RHEL clone)  least following Python versions are available:

- AlmaLinux 8
  - python27
  - python38
  - python39

- AlmaLinux 9
  - python39

Imho one should not use Python for "finished" stable programs...Python has imho too much OpsDev inside...and it looks like long stable APIs and backwards compatibility has not much focus in that particular language....on each *minor* version change one can only hope that the "finished" stable program it's still running without issues (and issue mostly do not mean display warnings, but simple crash with Python call trace...)

**Comment by martin-a-brown** [comment]
> Is there no "legacy" older version of Python available for Ubuntu 22.04 LTS?

There probably is.

> Python has imho too much OpsDev inside...and it looks like long stable APIs and backwards compatibility has not much focus in that particular language....on each minor version change one can only hope that the "finished" stable program it's still running without issues (and issue mostly do not mean display warnings, but simple crash with Python call trace...)

Definitely could have chosen something else when writing this.  It's what I selected at the time and with some thought toward supporting both the late 2.x series and the 3.4 or 3.5 releases at the time, I tried to choose the most likely to be stable modules and features of the language.

This software has seen almost zero of my attention since about 2016, so not a terrible run of stability given that the language is Python.

Anyway, language ecosystems and choices aside, I have found that the issue at hand is simply that the `collections` module moved the MutableMapping from `collections` to `collections.abc` around Python3.8.  This is not a terribly complicated fix and I'm taking the opportunity to perform other obvious "modernization".

**Comment by martin-a-brown** [comment]
Fixed by https://github.com/tLDP/python-tldp/pull/10

The two bugs that prevented `ldptool` from running are now fixed.

There's might be something more to be done, but the tooling should once again work.

I'll experiment some more and when I think it's working suitably, I'll bump the version.
